spring:
  application:
    name: mykingdom-imking
  datasource:
    url: jdbc:mysql://122.112.238.95:3389/imking?useSSL=false&useUnicode=true&characterEncoding=UTF8
#   url: jdbc:mysql://localhost:3306/imking?useSSL=false&useUnicode=true&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: imking
    password: 46OMuh4j
#    username: root
#    password: admin
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 10
      max-wait: 10
    schema: classpath:create-db.sql
    data: classpath:demo-data.sql
    initialize: true
    continue-on-error: true
#  redis:
#    host: 192.168.0.3
#    port: 6379
#    password:
  upload:
    path: /data/mydata
  jackson:
    time-zone: GMT+8

server:
  port: 8080
  context-path: /
  tomcat:
    uri-encoding: UTF-8

pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql

#logging:
#  config: classpath:log4j2.xml

mybatis:
  configuration:
    cache-enabled: false
    aggressive-lazy-loading: false
    use-generated-keys: false
    auto-mapping-behavior: partial
    default-executor-type: reuse
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    local-cache-scope: statement
#  type-handlers-package: